
; SPDX-FileName: FUEL.inc
; SPDX-FileCopyrightText: Fort Apocalypse © 1995, 2007, 2015 Steve Hales.
; SPDX-FileContributor: Modified by Scott Giese 2023
; SPDX-License-Identifier: CC-BY-NC-ND-2.5


BASE_SHAPE      .byte $00,$00,$00,$00,$00,$00    ; .... .... .... .... .... ....
                .byte $00,$00,$00,$00,$00,$00    ; .... .... .... .... .... ....
                .byte $00,$00,$00,$00,$00,$00    ; .... .... .... .... .... ....
                .byte $00,$00,$00,$00,$00,$00    ; .... .... .... .... .... ....
                .byte $44,$44,$44,$44,$44,$44    ; G.G. G.G. G.G. G.G. G.G. G.G.
                .byte $55,$58,$58,$58,$58,$56    ; GGGG GGR. GGR. GGR. GGR. GGGR
                .byte $55,$26,$35,$25,$2C,$56    ; GGGG .RGR .#GG .RGG .R#. GGGR
                .byte $55,$58,$58,$58,$58,$56    ; GGGG GGR. GGR. GGR. GGR. GGGR
                .byte $54,$00,$00,$00,$00,$54    ; GGG. .... .... .... .... GGG.
